# (string) Title of your wiki
title: KnowledgeSharing
demo_ver: 1.0.22
remote_theme: Drassil/git-wiki-theme@master
description: 一位喜欢中国传统文化的CICD技术宅男的分享
show_downloads: true
show_wiki_pages: true
show_wiki_pages_limit: 10
paginate: 2
paginate_path: "/assets/blog/page:num"
permalink: "/assets/blog/posts/:year/:month/:day/:title:output_ext"
blog_feature: true
show_wiki_posts: true
show_wiki_posts_limit: 5
logo_url: assets/images/1200px-Wikipedia-logo-v2.svg_.png
google_analytics:
git_branch: gh-pages
use_github_wiki: false
use_prose_io: true
service: github
search_engine : "js"
google_cse_token: 007197903287787072094:8rbvkeqo6qw
wiki_folder : "wiki"
site_root: 

#
# Jekyll
#

defaults:
 - 
    scope:
      path: "wiki"
    values:
      permalink: /:basename
 -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "git-wiki-default"
 -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "git-wiki-default"
 -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "git-wiki-post"
 -
    scope:
      path: assets/blog
    values:
      layout: "git-wiki-blog"

plugins:
 - jekyll-feed
 - jekyll-redirect-from
 - jekyll-seo-tag
 - jekyll-sitemap
 - jekyll-avatar
 - jemoji
 - jekyll-mentions
 - jekyll-spaceship
  
#
# INCLUDING HOOKS
# They are optional, change them only if you need
# Check wiki documentation to learn how they work
#

inc_after_content: "drassil/comments.html"
inc_after_head : "drassil/head.html"
inc_before_page_list : "drassil/sidebar.html"

# Where things are
jekyll-spaceship:
  # default enabled processors
  processors:
    - table-processor
    - mathjax-processor
    - plantuml-processor
    - mermaid-processor
    - polyfill-processor
    - media-processor
    - emoji-processor
    - element-processor
  mathjax-processor:
    src:
      - https://polyfill.io/v3/polyfill.min.js?features=es6
      - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    config:
      tex:
        inlineMath:
          - ['$','$']
          - ['\(','\)']
        displayMath:
          - ['$$','$$']
          - ['\[','\]']
      svg:
        fontCache: 'global'
    optimize: # optimization on building stage to check and add mathjax scripts
      enabled: true # value `false` for adding to all pages
      include: []   # include patterns for math expressions checking (regexp)
      exclude: []   # exclude patterns for math expressions checking (regexp)
  plantuml-processor:
    mode: default  # mode value 'pre-fetch' for fetching image at building stage
    css:
      class: plantuml
    syntax:
      code: 'plantuml!'
      custom: ['@startuml', '@enduml']
    src: http://www.plantuml.com/plantuml/svg/
  mermaid-processor:
    mode: default  # mode value 'pre-fetch' for fetching image at building stage
    css:
      class: mermaid
    syntax:
      code: 'mermaid!'
      custom: ['@startmermaid', '@endmermaid']
    config:
      theme: default
    src: https://mermaid.ink/svg/
  media-processor:
    default:
      id: 'media-{id}'
      class: 'media'
      width: '100%'
      height: 350
      frameborder: 0
      style: 'max-width: 600px; outline: none;'
      allow: 'encrypted-media; picture-in-picture'
  emoji-processor:
    css:
      class: emoji
    src: https://github.githubassets.com/images/icons/emoji/